services:
  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    ports:
      - 8989:8989
    volumes:
      - ./config/sonarr:/config # Config
      - /media:/data
    restart: unless-stopped
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    ports:
      - 7878:7878
    volumes: 
      - ./config/radarr:/config # Config
      - /media:/data
    restart: unless-stopped
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    ports:
      - 6767:6767
    volumes:
      - ./config/bazarr:/config # Config
      - /media:/data
    restart: unless-stopped
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    ports:
      - 9696:9696
    volumes:
      - ./config/prowlarr:/config # Config
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ./config/qbittorrent:/config # Config
      - /media:/data/
      
    ports:
      - 8999:8080
      - 6999:6881
      - 6999:6881/udp
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
      - JELLYFIN_PublishedServerUrl=https://kaficacraft.hopto.org
    volumes:
      - ./config/jellyfin:/config # Config
      - /media:/data
    ports:
      - 8096:8096
    restart: unless-stopped
  
